apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: hdfs-sub
  namespace: kubedatastack-operators
spec:
  channel: stable
  name: hdfs-operator
  source: hdfs-catalog
  sourceNamespace: olm
  installPlanApproval: Automated